name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt-get install -y xvfb
          pip3 install -r requirements.txt
      - name: Run test cases
        run: |
          export PYTHONPATH='$PYTHONPATH:./'
          xvfb-run -a nosetests-3.4 -vs --nologcapture --tc-file=config.ini testcases
